Web/ViewModels/House/AddHouseViewModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using Web.CustomDataAnnotations;

namespace Web.ViewModels.House
{
    public class AddHouseViewModel : HouseViewModel
    {
        [Required(ErrorMessage = "Pick an Image")]
        public override IFormFile ImageUploaded { get; set; }
    }
}

Web/ViewModels/House/DetailsHouseViewModel.cs
using System.Collections.Generic;
namespace Web.ViewModels.House
{
    using Entities;
    public class DetailsHouseViewModel
    {
        public Entities.House House { get; set; }
        public ICollection<Feature> FeaturesToDisplay { get; set; }
    }
}

Web/ViewModels/House/HouseViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using Web.CustomDataAnnotations;

namespace Web.ViewModels.House
{
    public class HouseViewModel
    {
        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Price is required")]
        public double Price { get; set; } = 200;

        [Required(ErrorMessage = "Bedrooms is required")]
        public int Bedrooms { get; set; } = 1;
        [Required(ErrorMessage = "Bathrooms is required")]
        public int Bathrooms { get; set; } = 1;
        [Required(ErrorMessage = "Size is required")]
        public double Size { get; set; } = 225;
        public SelectList Provinces { get; set; }
        [Display(Name = "Province")]
        [Required(ErrorMessage = " Pick a Province")]
        public int ProvinceId { get; set; }
        [Display(Name = "Image")]
        [AllowedExtensions(new string[] { ".jpg", ".jpeg", ".png" },
                    ErrorMessage = "Your image's filetype is not valid.")]
        public virtual IFormFile ImageUploaded { get; set; }
        [Required]
        [MinLength(50, ErrorMessage = "The description should include at least 50 characters")]
        [MaxLength(255, ErrorMessage = "Is too long, 255 characters is the maximum")]
        public string Description { get; set; }
        public IEnumerable<Feature> Features { get; set; } = new List<Feature>();
        public IEnumerable<HouseFeature> SelectedFeatures { get; set; } = new List<HouseFeature>();
        public IEnumerable<Service> Services { get; set; } = new List<Service>();
        public IEnumerable<HouseService> SelectedServices { get; set; } = new List<HouseService>();
    }
}

Web/ViewModels/House/UpdateHouseViewModel.cs
using System.Collections.Generic;
using Entities;

namespace Web.ViewModels.House
{
    public class UpdateHouseViewModel : HouseViewModel
    {
        public int HouseId { get; set; }
        public string ImageName { get; set; }
    }
}

Web/ViewModels/Rent/InvoiceViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Entities;

namespace Web.ViewModels.Rent
{
    public class InvoiceViewModel
    {
        public int HouseId { get; set; }
        public double Price { get; set; }
        [Display(Name = "From")]
        [Required(ErrorMessage = "When do you want to start living here????")]
        public string From { get; set; }
        [Display(Name = "Months to Stay")]
        [Required(ErrorMessage = "How long will you stay here???")]
        public int Months { get; set; } = 1;
        [Display(Name = "To")]
        public string To { get; set; } = DateTime.Now.AddMonths(1).ToString("MM.dd.yyyy");
        public ICollection<Service> ServicesToDisplay { get; set; } = new List<Service>();
        public ICollection<Service> SelectedServices { get; set; } = new List<Service>();
        public double HomeSubTotal { get => Price * Months; set => this.HomeSubTotal = value; }
        public double ServicesSubTotal { get => SelectedServices.Sum(s => s.Price); set => this.ServicesSubTotal = value; }
        public double SubTotal { get => HomeSubTotal + ServicesSubTotal; set => this.SubTotal = value; }
        public double Tax { get => SubTotal * 0.13; set => this.Tax = value; }
        public double Total { get => SubTotal + Tax; set => this.Total = value; }
    }
}

Web/ViewModels/Rent/RentListViewModel.cs
using System.Collections.Generic;
using Entities;
namespace Web.ViewModels.Rent
{
    public class RentListViewModel
    {
        public IEnumerable<Entities.House> Houses { get; set; }
        public IEnumerable<Province> Provinces { get; set; }
        public IEnumerable<Feature> Features { get; set; }
        public string ProvinceToCheck { get; internal set; }
    }
}

Web/Controllers/HouseController.cs
using System.Reflection.Emit;
using System.Net;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Entities;
using Repositories.Context;
using Services.Generic;
using Web.ViewModels.House;
using AutoMapper;
using Services;
using Microsoft.AspNetCore.Authorization;

namespace Web.Controllers
{
    public class HouseController : Controller
    {
        private readonly IHouseService _houseService;
        private readonly IGenericService<Province> _provinceService;
        private readonly IGenericService<Feature> _featureService;
        private readonly IMapper _autoMapper;
        private readonly IGenericService<Service> _servicexService;

        public HouseController(IHouseService houseService, IGenericService<Province> provinceService, IGenericService<Feature> featureService, IMapper autoMapper, IGenericService<Service> servicexService)
        {
            this._houseService = houseService;
            this._provinceService = provinceService;
            this._featureService = featureService;
            this._autoMapper = autoMapper;
            this._servicexService = servicexService;
        }

        // GET: House
        [Authorize(Roles = "Admin,SuperAdmin")]
        public IActionResult List()
        {
            return View(_houseService.GetAll());
        }

        // GET: House/Create
        [Authorize(Roles = "Admin,SuperAdmin")]
        public IActionResult Create()
        {
            var model = new AddHouseViewModel()
            {
                Provinces = new SelectList(_provinceService.GetAll(), "ProvinceId", "Name"),
                Features = _featureService.GetAll(),
                Services = _servicexService.GetAll()
            };
            return View(model);
        }

        // POST: House/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,SuperAdmin")]
        public IActionResult Create(AddHouseViewModel model, IEnumerable<int> features, IEnumerable<int> services)
        {
            if (ModelState.IsValid)
            {
                var house = _autoMapper.Map<House>(model);
                house.IsItAvailable = true;
                var houseFeatures = features.Select(id => new HouseFeature() { FeatureId = id });
                foreach (var id in features)
                {
                    house.Features.Add(new HouseFeature() { FeatureId = id });
                }
                var houseServices = services.Select(id => new HouseService() { ServiceId = id });
                foreach (var id in services)
                {
                    house.Services.Add(new HouseService() { ServiceId = id });
                }
                _houseService.Insert(house, model.ImageUploaded);
                _houseService.Save();
                TempData["TransactionCompleted"] = "House added Sucessfully";
                return RedirectToAction(nameof(List));
            }

            model.Provinces = new SelectList(_provinceService.GetAll(), "ProvinceId", "Name");
            model.Features = _featureService.GetAll();
            model.SelectedFeatures = features.Select(id => new HouseFeature() { FeatureId = id });
            model.Services = _servicexService.GetAll();
            model.SelectedServices = services.Select(id => new HouseService() { ServiceId = id });
            return View(model);
        }

        // GET: House/Edit/5
        [Authorize(Roles = "Admin,SuperAdmin")]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var house = _houseService.GetById(id.Value);
            if (house == null)
            {
                return NotFound();
            }
            var model = _autoMapper.Map<UpdateHouseViewModel>(house);
            model.Provinces = new SelectList(_provinceService.GetAll(), "ProvinceId", "Name");
            model.Features = _featureService.GetAll();
            model.SelectedFeatures = house.Features;
            model.Services = _servicexService.GetAll();
            model.SelectedServices = house.Services;
            return View(model);
        }

        // // POST: House/Edit/5
        // // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,SuperAdmin")]
        public IActionResult Edit(int id, [Bind("HouseId,ImageName,Name,Price,Bedrooms,Bathrooms,Size,ProvinceId,ImageUploaded,Description")] UpdateHouseViewModel model, IEnumerable<int> features, IEnumerable<int> services)
        {
            if (id != model.HouseId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var house = _autoMapper.Map<House>(model);
                foreach (var featureId in features)
                {
                    house.Features.Add(new HouseFeature() { HouseId = model.HouseId, FeatureId = featureId });
                }
                var houseServices = services.Select(id => new HouseService() { ServiceId = id });
                foreach (var serviceId in services)
                {
                    house.Services.Add(new HouseService() { HouseId = model.HouseId, ServiceId = serviceId });
                }
                _houseService.Update(house, model.ImageUploaded);
                _houseService.Save();
                TempData["TransactionCompleted"] = "House edited Sucessfully";
                return RedirectToAction(nameof(List));
            }
            model.Provinces = new SelectList(_provinceService.GetAll(), "ProvinceId", "Name", model.ProvinceId);
            model.Features = _featureService.GetAll();
            model.SelectedFeatures = features.Select(id => new HouseFeature() { FeatureId = id });
            model.Services = _servicexService.GetAll();
            model.SelectedServices = services.Select(id => new HouseService() { ServiceId = id });
            return View(model);
        }
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var house = _houseService.GetById(id.Value);
            if (house == null)
            {
                return NotFound();
            }
            var houseFeatures = _featureService.GetAll().Where(f => house.Features.Any(hf => hf.FeatureId == f.FeatureId));
            var model = new DetailsHouseViewModel
            {
                House = house,
                FeaturesToDisplay = houseFeatures.ToList()
            };
            return View(model);
        }
    }
}

Web/Controllers/RentController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Services;
using Services.Generic;
using Web.ViewModels.Rent;
//using Web.Models;

namespace Web.Controllers
{
    public class RentController : Controller
    {
        private readonly IHouseService _houseService;
        private readonly IGenericService<Province> _provinceService;
        private readonly IGenericService<Feature> _featureService;
        private readonly IGenericService<Service> _serviceService;
        private readonly IMapper _autoMapper;
        private readonly UserManager<AppUser> _userManager;
        private readonly IInvoiceService _InvoiceService;

        public RentController(IHouseService houseService, IGenericService<Province> provinceService, IGenericService<Feature> featureService, IGenericService<Service> serviceService, IMapper autoMapper, UserManager<AppUser> userManager, IInvoiceService invoiceService)
        {
            this._houseService = houseService;
            this._provinceService = provinceService;
            this._featureService = featureService;
            this._serviceService = serviceService;
            this._autoMapper = autoMapper;
            this._userManager = userManager;
            this._InvoiceService = invoiceService;
        }

        public async Task<IActionResult> List(string province = null)
        {
            await Task.Yield();
            var model = new RentListViewModel()
            {
                Houses = province == null ? _houseService.GetByAvailability().OrderBy(h => h.Price) : _houseService.GetAll().Where(h => h.Province.Name == province).OrderBy(h => h.Price),
                Features = _featureService.GetAll(),
                Provinces = _provinceService.GetAll(),
                ProvinceToCheck = province
            };

            return View(model);
        }
        [Authorize(Roles = "Customer,SuperAdmin")]
        public async Task<IActionResult> House(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var house = _houseService.GetById(id.Value);
            if (house == null)
            {
                return NotFound();
            }
            if (!house.IsItAvailable)
            {
                return RedirectToAction("NotAvailable", "Show");
            }

            var model = new InvoiceViewModel
            {
                HouseId = house.HouseId,
                Price = house.Price,
                ServicesToDisplay = house.Services.Select(s => s.Service).ToList()
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult HouseAsync(InvoiceViewModel model, IEnumerable<int> service)
        {
            if (ModelState.IsValid)
            {
                var invoice = _autoMapper.Map<Invoice>(model);
                invoice.CustomerId = _userManager.GetUserId(User);
                _InvoiceService.Insert(invoice, service);
                _InvoiceService.Save();
                TempData["TransactionComplete"] = true;
                return RedirectToAction("Customer", "Invoice");
            }
            var house = _houseService.GetById(model.HouseId);
            var services = house.Services.Select(s => s.Service);
            model.ServicesToDisplay = services.ToList();
            return View(model);
        }

    }
}

Web/Views/Rent/House.cshtml
@using Web.Helpers
@{
  ViewData["Title"] = "House";
  Layout = "_RentHouseLayout";
  var today = DateTime.Now.ToString("yyyy/MM/dd");
  var next10days = DateTime.Now.AddDays(10).ToString("yyyy/MM/dd");
}
@section CSS{
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bs-stepper/dist/css/bs-stepper.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/material_red.css">
    <link rel="stylesheet" href="~/css/renthouse.css">
}

@model InvoiceViewModel
<div class="container my-3">
    <div class="row justify-content-center align-items-center">
        <div class="bs-stepper">
          <div class="bs-stepper-header" role="tablist">
            <!-- your steps here -->
            <div class="step" data-target="#logins-part">
              <button type="button" class="step-trigger" role="tab" aria-controls="logins-part" id="logins-part-trigger">
                <span class="bs-stepper-circle">1</span>
                <span class="bs-stepper-label">Rent Details</span>
              </button>
            </div>
            <div class="line"></div>
            <div class="step" data-target="#information-part">
              <button type="button" class="step-trigger" role="tab" aria-controls="information-part" id="information-part-trigger">
                <span class="bs-stepper-circle">2</span>
                <span class="bs-stepper-label">Credit Card Information</span>
              </button>
            </div>
          </div>
  <div class="bs-stepper-content">
    <!-- your steps content here -->
    <div id="logins-part" class="content fade" role="tabpanel" aria-labelledby="logins-part-trigger">
    <form method="post" asp-controller="Rent" asp-action="House" id="rent-form">
        <div class="row">
          <div class="col-7">
            <input type="hidden" asp-for="HouseId">
            <input type="hidden" asp-for="Price">
            <h5 class="text-center fw-bold">Rent Details</h5>
            <div class="mb-4">
              <label asp-for="From" class="form-label"></label>
              <input asp-for="From" class="form-control">
            <div class="invalid-feedback" id='from-error-message'></div>
            </div>
            <div class="form-outline mt-3 mb-4">
              <input asp-for="Months" class="form-control" min="1">
              <label asp-for="Months" class="form-label"></label>
            <div class="invalid-feedback" id='months-error-message'></div>
            </div>
            <div class="form-outline mt-2 mb-4">
              <input asp-for="To" class="form-control" readonly>
              <label asp-for="To" class="form-label"></label>
            <div class="invalid-feedback" id='to-error-message'></div>
            </div>
            <hr>
            <h5 class="text-center fw-bold my-4">Services</h5>
            @foreach (var service in Model.ServicesToDisplay)
                {
                                              <div class="form-check">
                                                  <input type="checkbox" name="service" value="@service.ServiceId" class="form-check-input" >
                                                  <label class="form-check-label" >
                      @service.Name <span class="badge rounded-pill bg-warning text-dark">@service.Price.ToCurrency()</span>
                                                  </label>
                                              </div>
                }
            <hr>
            <div class="text-end"><button type="button" class="btn btn-primary" id="next-btn"><i class="fas fa-arrow-right"></i> Next</button></div>
          </div>
          <div class="col-5 py-3" id="rent-costs">
                <h5 class="text-center fw-bold">Costs</h5>
                <p><span>Home:</span> <span class="lead fw-bold" id="homeSubTotal">@Model.HomeSubTotal.ToCurrency()</span></p>
                <p><span>Services:</span> <span class="lead fw-bold" id="serviceSubTotal">@Model.ServicesSubTotal.ToCurrency()</span></p>
                <p><span>Subtotal:</span> <span class="lead fw-bold" id="subTotal">@Model.SubTotal.ToCurrency()</span></p>
                <p><span>Tax:</span> <span class="lead fw-bold" id="tax">@Model.Tax.ToCurrency()</span></p>
                <h2 class="fw-bold">Total:</h2>
                <h1 class="fw-bold" id="total">@Model.Total.ToCurrency()</h1>
          </div>
        </div>
            </form>
    </div>
    <div id="information-part" class="content fade" role="tabpanel" aria-labelledby="information-part-trigger">
                  <!-- Credit Card Picture -->
            <div class="card-wrapper"></div>
            <!-- Form -->
            <form action="#" method="POST" id="credit-card-form">

                <div class="form-outline mb-2 mt-4">
                    <i class="far fa-credit-card trailing"></i>
                    <input class="form-control form-icon-trailing" id="number"/>
                    <label class="form-label">Card number</label>
                    <div class="invalid-feedback" id='to-error-message'>Invalid credit card number</div>
                </div>
                <div class="form-outline mt-4">
                    <input type="text" id="name" class="form-control" id="name"/>
                    <label class="form-label" for="name">Name on Card</label>
                    <div class="invalid-feedback">Invalid name</div>
                </div>
                <div class="row">
                  <div class="col-6">
                    <div class="form-outline mt-4">
                        <input type="text" id="expiry" class="form-control" placeholder="mm/yy"/>
                        <label class="form-label" for="name">Expiry Date</label>
                        <div class="invalid-feedback">Invalid expiration date</div>
                    </div>
                  </div>
                  <div class="col-6">
                    <div class="form-outline mt-4">
                        <i class="fas fa-info trailing"></i>
                        <input id="cvc" class="form-control form-icon-trailing" />
                        <label class="form-label">Security Code</label>
                        <div class="invalid-feedback">Invalid cvv/cdd</div>
                    </div>
                  </div>
                </div>
                <div class="d-flex justify-content-between">
                  <button type="button" class="mt-4 btn btn-primary" id="previous-btn"><i class="fas fa-arrow-left"></i> Previous</button>
                  <button type="button" class="mt-4 btn btn-success" id="confirmation-btn"><i class="fas fa-check-circle"></i> Confirm Payment</button>
                </div>
            </form>
        </div>
    </div>
  </div>
</div>

    </div>
</div>
@section Scripts{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/luxon@1.26.0/build/global/luxon.min.js"></script>
    <script src="https://unpkg.com/currency.js@2.0.3/dist/currency.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bs-stepper/dist/js/bs-stepper.min.js"></script>
    <script src="~/lib/node_modules/card/dist/card.js"></script>
    <script src="~/js/Rent/bundle.js"></script>
}